### ISSUE TITLE
Default Contant-Type is 'text/html'

### ISSUE THREAD

**Issue by okbp** [dbcls/sparql-proxy#12] opened 2019-12-05 10:38 UTC
When the Content-Type header and Accept headers are omitted in the HTTP request, sparql-proxy does not return query results.
It seems returns HTML contents(with Content-Type='text/html').

There was no problem with the previous version(Created: 2019-03-13T07:20:10).
Has the specification changed?

I recommend sparql-proxy returns json data("application/sparql-results+json") as default.

**Comment by ursm** [comment] 2019-12-05 13:53
This seems to be caused by changing the query form page path to `/sparql` as well as the endpoint with the following commit:
https://github.com/dbcls/sparql-proxy/pull/7/commits/3e1b5653cf71899aeaba77677ca02a5cc2be0c85#diff-e6a5b42b2f7a26c840607370aed5301aR74

We were optimistic that the API client would not include `text/html` in the Accept header, but that was a bad idea now.

@ktym What do you think?

**Comment by ktym** [comment] 2019-12-06 07:56
I think to be compatible with the existing triple store, sparql-proxy should provide /sparql as HTML form and SPARQL endpoint, so if a user needs to retrieve SPARQL Results JSON Format, it should be explicitly indicated in the Accept header.

@okbp Could you explain in which case you had this problem and how hard to add the Accept header?

**Comment by okbp** [comment] 2019-12-10 06:16
@ktym 
I'm developping an application with [togostanza-gem](https://github.com/togostanza/togostanza-gem) and sparql-proxy.
But They cannot set request header ​​in the togostanza-gem.
https://github.com/togostanza/togostanza-gem/blob/master/lib/togostanza/stanza/querying.rb#L10 

For running my application, modification of either togostanza-gem or aparql-proxy is required.
If I fix the stanza-gem, I will implement as below.
I'll add third argument to query method, and if the third argument is not specified, I'll append the request header "Accept => 'application/sparql-results+json'" by default.

**Comment by ktym** [comment] 2020-06-11 05:59
Just to close this issue, any SPARQL clients accessing SPARQL-proxy should use the "Accept => 'application/sparql-results+json'" header. As one of these clients, togostaza-gem is updated to include the header since the version 2.2.1.

https://github.com/togostanza/togostanza-gem/commit/c7657e9e591d523af0e24bf44399d48d62390fc2

**Closed by ktym** 2020-06-11 05:59 UTC
